# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "TRAVEL_APP_DB"
      POSTGRES_USER: "yoo"
      POSTGRES_PASSWORD: "Bs52#gET*RsQ4G7Xm%Fs"
    ports:
      - 5432:5432
    expose:
      - 5432
